name: Sync Trends Every 6 Hours

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:      # optional manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run trend sync script
        run: npm run sync-trends
